package leet.code.find.the.difference;

public class Solution {

    public char findTheDifference(String s, String t) {
        char xor = 0;
        for (int i = 0; i < t.length(); i++) {
            xor ^= t.charAt(i);
            if (i != s.length()) xor ^= s.charAt(i);
        }
        return xor;
    }

    /**
     * You are given two strings s and t.
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * Return the letter that was added to t.
     *
     * Example 1:
     * Input: s = "abcd", t = "abcde"
     * Output: "e"
     * Explanation: 'e' is the letter that was added.
     *
     * Example 2:
     * Input: s = "", t = "y"
     * Output: "y"
     */
    public static void main(String[] args) {
        Solution solution = new Solution();
        System.out.println(solution.findTheDifference("abcd", "abcde"));
        System.out.println(solution.findTheDifference("", "y"));
    }
}
